// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVikoj4G4CKrlNlCFqPwgywZd6UBgG1Po',
    appId: '1:1072950734327:web:ae8be75e911abb310492f2',
    messagingSenderId: '1072950734327',
    projectId: 'ridenow-app-3aa76',
    authDomain: 'ridenow-app-3aa76.firebaseapp.com',
    storageBucket: 'ridenow-app-3aa76.firebasestorage.app',
    measurementId: 'G-ZMF0K7QJSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf-j4D_x5hTXQxmzmukrklKU9D0vul36o',
    appId: '1:1072950734327:android:65459955fde88bf50492f2',
    messagingSenderId: '1072950734327',
    projectId: 'ridenow-app-3aa76',
    storageBucket: 'ridenow-app-3aa76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALaE-wKMWcfVScpPfWIXcZGvfB7M8-nP4',
    appId: '1:1072950734327:ios:f982cb798a7818310492f2',
    messagingSenderId: '1072950734327',
    projectId: 'ridenow-app-3aa76',
    storageBucket: 'ridenow-app-3aa76.firebasestorage.app',
    iosBundleId: 'com.example.rideNowKhoaluan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALaE-wKMWcfVScpPfWIXcZGvfB7M8-nP4',
    appId: '1:1072950734327:ios:f982cb798a7818310492f2',
    messagingSenderId: '1072950734327',
    projectId: 'ridenow-app-3aa76',
    storageBucket: 'ridenow-app-3aa76.firebasestorage.app',
    iosBundleId: 'com.example.rideNowKhoaluan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVikoj4G4CKrlNlCFqPwgywZd6UBgG1Po',
    appId: '1:1072950734327:web:650cf32aeb2d06ca0492f2',
    messagingSenderId: '1072950734327',
    projectId: 'ridenow-app-3aa76',
    authDomain: 'ridenow-app-3aa76.firebaseapp.com',
    storageBucket: 'ridenow-app-3aa76.firebasestorage.app',
    measurementId: 'G-BP379VCQE0',
  );
}
